Update web-analytics.rst
italia/manuale-operativo-design-docs pull request #30
Opened 2022-11-04 10:21 UTC by danielaiozzo

a content fix for the web analytics section

2022-11-04 18:19 UTC, Fupete requested changes

2022-11-04 18:19 UTC, Fupete commented on doc/design-research/web-analytics.rst
> +Il servizio WAI si colloca nel contesto delle `Linee guida di design per i servizi digitali della PA <https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/>`__ italiana,
Url e titolo LG è sbagliato. Corretto sarebbe: 
`Linee guida di design per i siti internet e i servizi digitali della PA <https://docs.italia.it/italia/design/lg-design-servizi-web/it/versione-corrente/index.html>`

2022-11-04 18:19 UTC, Fupete commented on doc/design-research/web-analytics.rst
> +Il servizio WAI si colloca nel contesto delle `Linee guida di design per i servizi digitali della PA <https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/>`__ italiana,
Segnalo, solo come promemoria, anche che il corrente [Piano Triennale 2021–2023](https://www.agid.gov.it/it/agenzia/piano-triennale) non è mai stato riportato sul sito dedicato al Piano Triennale https://pianotriennale-ict.italia.it o su Docs Italia, fermi al Piano 2020–2022 🤷

2022-11-04 18:19 UTC, Fupete commented on doc/design-research/web-analytics.rst
> +Il servizio WAI si colloca nel contesto delle `Linee guida di design per i servizi digitali della PA <https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/>`__ italiana,
cc @danielaiozzo ⬆️ qui sopra 2 commenti

2022-11-07 08:29 UTC, pedromaria88 requested changes

2022-11-07 08:29 UTC, pedromaria88 commented on doc/design-research/web-analytics.rst
>  -  `Installazione e configurazione di Matomo
-  `Scheda software Plausible analytics
   <https://developers.italia.it/it/software/italia-software-matomo-32c75d>`__

2022-11-07 08:29 UTC, pedromaria88 commented on doc/design-research/web-analytics.rst
>  -  `Installazione e configurazione di Matomo
Per simmetria, come primo riferimento di Matomo punterei al catalogo Developers Italia

2022-11-07 08:29 UTC, pedromaria88 commented on doc/design-research/web-analytics.rst
>     <https://matomo.org/faq/on-premise/installing-matomo/>`__
Eliminerei il link a un'installazione on premise, in ragione della strategia cloud.

2022-11-07 10:27 UTC, danielaiozzo reviewed
ok

2022-11-07 10:27 UTC, danielaiozzo commented on doc/design-research/web-analytics.rst
> +Il servizio WAI si colloca nel contesto delle `Linee guida di design per i servizi digitali della PA <https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/>`__ italiana,
```suggestion
Il servizio WAI si colloca nel contesto delle `Linee guida di design per i siti internet e i servizi digitali della PA <https://docs.italia.it/italia/design/lg-design-servizi-web/it/versione-corrente/index.html>`__ italiana, oltre che nel Piano Triennale per l'Informatica nella PA. 
```

2022-11-07 10:27 UTC, danielaiozzo commented on doc/design-research/web-analytics.rst
> +Il servizio WAI si colloca nel contesto delle `Linee guida di design per i servizi digitali della PA <https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/>`__ italiana,
ok @Fupete a questo punto piano triennale non lo linkiamo proprio, che dici?

2022-11-14 15:02 UTC, merged